# Generated by Django 2.1.7 on 2019-04-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='this is cool!')),
                ('description', models.TextField(default='this is cool!')),
                ('price', models.TextField(default='this is cool!')),
                ('summary', models.TextField(default='this is cool!')),
                ('dummy', models.TextField(default='this is cool!')),
            ],
        ),
    ]
