# Generated by Django 2.1.7 on 2019-04-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Productss',
        ),
    ]
