# Generated by Django 2.1.7 on 2019-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.TextField(default='Summary'),
        ),
    ]
